---
volumes:
  portainer-data:
    driver: local
  open-meteo-data:
    driver: local
  wakeword:
    driver: local
services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    ports:
      - 7772:3000
    volumes:
      - ./homepage/config:/app/config # Make sure your local config directory exists
      - /var/run/docker.sock:/var/run/docker.sock # (optional) For docker integrations
    restart: unless-stopped
  portainer:
    container_name: portainer
    image: docker.io/portainer/portainer-ce:latest
    ports:
      - 9000:9000
      - 9443:9443
      - 8000:8000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer-data:/data
    restart: unless-stopped
  ntfy:
    image: binwiederhier/ntfy
    container_name: ntfy
    ports:
      - 7770:80
    command: ["serve"]
    restart: unless-stopped
  home-web:
    image: home-web:1
    container_name: home-web
    ports:
      - 7771:80
    restart: unless-stopped
  home-server:
    image: home-server:1
    container_name: home-server
    ports:
      - 7773:7777
    restart: unless-stopped
  open-meteo: # https://github.com/open-meteo/open-meteo/blob/main/docs/getting-started.md
    image: ghcr.io/open-meteo/open-meteo
    container_name: open-meteo
    ports:
      - 7775:8080
    volumes:
      - open-meteo-data:/app/data
    restart: unless-stopped
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    ports:
      - 8123:8123
    volumes:
      - ./home-assistant/config:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    restart: unless-stopped
    privileged: true
  piper:
    image: lscr.io/linuxserver/piper:latest
    container_name: piper
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - PIPER_VOICE=en_US-lessac-medium
      - PIPER_LENGTH=1.0 #optional
      - PIPER_NOISE=0.667 #optional
      - PIPER_NOISEW=0.333 #optional
      - PIPER_SPEAKER=0 #optional
      - PIPER_PROCS=1 #optional
    volumes:
      - ./piper/config:/config
    ports:
      - 10200:10200
    restart: unless-stopped
  faster-whisper:
    image: lscr.io/linuxserver/faster-whisper:latest
    container_name: faster-whisper
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WHISPER_MODEL=tiny-int8
      - WHISPER_BEAM=1 #optional
      - WHISPER_LANG=en #optional
    volumes:
      - ./whisper/config:/config
    ports:
      - 10300:10300
    restart: unless-stopped
  openwakeword:
    container_name: openwakeword
    image: rhasspy/wyoming-openwakeword
    user: 1001:1001
    ports:
      - 12202:12202/udp
    volumes:
      - wakeword:/data
      # - ./wakeword:/custom
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    # environment:
      # - TZ=Australia/Melbourne
    command: --preload-model 'ok_nabu' --custom-model-dir /custom
    restart: unless-stopped