---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/services

- AI Services:
    - Open Web UI:
        href: http://192.168.86.247:3000
        description: Open Web UI for Local AI Services
    - Ollama:
        href: http://192.168.86.247:11434
        description: Ollama Base Service
    - Stable Diffusion:
        href: http://192.168.86.247:7860
        description: Ollama Base Service

- Home Assistant Services:
    - Home Assistant:
        href: http://192.168.86.29:8123
        description: Home Assistant
    - Piper:
        href: http://192.168.86.247:10200
        description: Text to Speech 
    - Whisper:
        href: http://192.168.86.247:10300
        description: Speech to Text
    - openwakeword:
        href: http://192.168.86.247:12202
        description: Wake Word Service for HA

- Home Services:
    - Device Metrics:
        href: http://192.168.86.29:7773
        description: Device Metrics from Hubitat
    - Hubitat:
        href: http://192.168.86.30/
        description: Hubitat zWave+ IOT hub
    - Home Dashboard:
        href: http://192.168.86.29:7771
        description: Home Dashboard with Notifications
    - NTFY:
        href: http://192.168.86.29:7770
        description: Notification Service
    - Open Meteo:
        href: http://192.168.86.29:7775
        description: Open Weather Service

- Control Plane:
    - Homepage:
        href: http://192.168.86.29:7772
        description: Homepage is 😎
    - Portainer:
        href: http://192.168.86.29:9000
        description: Container visibility
